name: teknopos
description: "A simple POS app for WiFi voucher sales using AIO server."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  csv: ^5.0.1
  file_picker: ^5.2.10
  printing: ^5.12.0
  pdf: ^3.8.4
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.10
  excel: ^4.0.6
  path_provider: ^2.1.5
  sqflite: ^2.3.0
  path: ^1.8.3
  share_plus: ^7.2.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
